syntax on
filetype plugin indent on

let g:netrw_home=$XDG_STATE_HOME.'/vim'

set viminfofile=$XDG_STATE_HOME/vim/viminfo
set cursorline
set ruler
set relativenumber
set tabstop=2
set shiftwidth=2
set expandtab
set wrap
set noswapfile
set nobackup
set nohlsearch
set incsearch
set ignorecase
set smartcase
set scrolloff=8
set colorcolumn=80
